version: '3.8'

services:

  database:
      container_name: database_container
      image: mysql:8.3.0
      restart: always
      environment:
     
           MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
           MYSQL_DATABASE: ${MYSQL_DATABASE}
           MYSQL_USER: ${MYSQL_USER}
           MYSQL_PASSWORD: ${MYSQL_PASSWORD}
           PMA_HOST: ${PMA_HOST}
      env_file:
           - ./.env
      ports:
           - '3307:3306'
      volumes:
           - ./mysql:/var/lib/mysql

  adminer:
      image: adminer
      restart: always   
      ports:
        - 5000:8080

   
  php:
      container_name: php_container
      build:
          context: .
          dockerfile: ./php/Dockerfile
      ports:
          - '9000:9000'
      volumes:
          - ./app:/var/www/portofolio
      depends_on:
           - database


  nginx:
      image: nginx:stable-alpine
      container_name: nginx_container
      ports:
        - '8080:80'
      volumes:
          - ./app:/var/www/portofolio
          -  ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      depends_on:
          - php
          - database
          - node

  node:
      image: node:latest
      container_name: node_container
      volumes:
           - ./app:/var/www/portofolio
      working_dir: /var/www/portofolio
